a=input('enter time of 30 hourly observation')
b=input('enter time of origin:')
c=input('where the Meter go:')
d=str(input('wind speed v direction:'))
e=input('cloud_1 type:')
f=input('cloud_2 type:')
g=input('cloud_3 type/NSC:')
h=input('cloud_4 type/SKC:')
i=input('dry-bulb temp:')
j=input('wet-bulb temp:')
k=eval(input('C.L.P of digital bar:'))
l=eval(input('QNH of digital bar :'))
m=input('Dew point:')
n=input('relative humidity:')
o=input('present weather:').upper()
p=str(input('visibility/COVAK:'))
q=input('evaporation cups:')
r=input('Rainfall:')

k_r=round(k/70,2)
l_r=round(l/23,2)


print('*'*90)
print()
print(a+'z',end=',')
print(b+'z',end=',')
print(c,end=',')
print(d+'KT',end=',')
print(e,end=',')
print(f,end=',')
print(g,end=',')
print(h,end=',')
print(j,end=',')
print(i,end=',')
print(k,end=',')
print(k_r,'inch')
print(l,end=',')
print(l_r,'inch')
print(m,end=',')
print(n,end=',')
print(o,end=',')
print(p+'Km',end=',')
print(q)
print()
print('*'*90)